services:

  server:
    build: 
      context: ./server 
    container_name: rsvp-server 
    ports:
      - "3000:3000" 
    environment:
      - "NODE_ENV=production"
      - "PORT=3000" 
      - "MONGO_URI=${MONGO_URI}"
    command: npm start 
    
  client:
    build: 
      context: ./client 
    container_name: rsvp-client
    ports:
      - "80:80" 
    
    environment:
      - "VITE_API_BASE_URL=https://rsvp-event-gate.onrender.com" 
